services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      # Use host base URL (no /api suffix). API endpoints include the /api prefix in the client calls.
      - VITE_API_URL=http://localhost:4000
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./data:/data
    environment:
      - NODE_ENV=development