static_sites:
  - name: cookbook-frontend
    branch: main
    buildCommand: npm ci && npm run build
    publishPath: dist

services:
  - type: web
    name: cookbook-api
    branch: main
    plan: free
    region: oregon
    buildCommand: cd api && npm ci && npm run init-db
    startCommand: cd api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SQLITE_DB_PATH
        value: /opt/render/project/src/data/sqlite.db
    disk:
      name: cookbook-data-disk
      sizeGB: 5
      mountPath: /opt/render/project/src/data
